"""Books must have a quantity and penalty fee

Revision ID: 0984457632e6
Revises: 190eb0c12c45
Create Date: 2024-09-09 19:58:56.738497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0984457632e6'
down_revision = '190eb0c12c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_fee', sa.Integer(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('rental_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_fee', sa.INTEGER(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('penalty_fee')

    # ### end Alembic commands ###
