"""change rental to penalty

Revision ID: 2e6f35775fa1
Revises: bedbab00b5c7
Create Date: 2024-09-10 14:05:10.076464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6f35775fa1'
down_revision = 'bedbab00b5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_fee', sa.Integer(), nullable=True))
        batch_op.drop_column('rental_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_fee', sa.INTEGER(), nullable=True))
        batch_op.drop_column('penalty_fee')

    # ### end Alembic commands ###
