"""update: add book.books_borrowed

Revision ID: 6e31ad509ae9
Revises: 0984457632e6
Create Date: 2024-09-09 23:10:42.495019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e31ad509ae9'
down_revision = '0984457632e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('books_borrowed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('books_borrowed')

    # ### end Alembic commands ###
