"""change book.count to book.quantity

Revision ID: bedbab00b5c7
Revises: af227b412bd4
Create Date: 2024-09-08 14:07:12.105186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedbab00b5c7'
down_revision = 'af227b412bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
