"""update: new columns in the transactions table

Revision ID: e251c92eac60
Revises: 8d3d6602458f
Create Date: 2024-09-21 12:29:59.452930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e251c92eac60'
down_revision = '8d3d6602458f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issued_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('returned_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('charge', sa.Integer(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('charge')
        batch_op.drop_column('returned_on')
        batch_op.drop_column('issued_on')

    # ### end Alembic commands ###
