name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
        DEPLOY_PATH: "/home/ubuntu/BookNest-Server"
        FLASK_ENV: production
        GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Ensure Repository Exists
        run: |
            if [ ! -d "$DEPLOY_PATH" ]; then
                git clone https://x-access-token:${GH_PAT}@github.com/SymonMuchemi/BookNest-Server.git $DEPLOY_PATH
            fi

      - name: Stop Gunicorn
        run: sudo systemctl stop flaskapp

      - name: Copy files to app directory
        run: |
          rsync -av --exclude='.git*' ./ $DEPLOY_PATH/

      - name: Ensure virtualenv & install dependencies
        run: |
          cd $DEPLOY_PATH
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart Gunicorn
        run: sudo systemctl start flaskapp
